ports:
  - port: 8001
    onOpen: ignore
    visibility: private
  - port: 6379
    onOpen: ignore
    visibility: private
  - port: 3000
    visibility: public
    onOpen: open-browser
  - port: 3001
    visibility: public
    onOpen: open-browser

tasks:
  - name: Start Redis Stack
    init: |
     docker-compose pull
    command: |
     alias redis-cli="docker exec -it redis-stack redis-cli" 
     echo "Use redis-cli to interact with Redis here."
     docker-compose up -d
     gp sync-done finished
    openMode: tab-after
  
  - name: Start Node Stack1
    init: | 
     npm i
    command: gp sync-await finished && npm run start
    openMode: tab-after
    env:
      PORT: 3000

  - name: Start Node Stack2
    init: | 
     npm i
    command: gp sync-await finished && npm run start
    openMode: tab-after
    env:
      PORT: 3001

github: 
  prebuilds:
    master: true
    branches: true
    pullRequests: true